eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: niit1234
    url: jdbc:mysql://127.0.0.1:3306/springcloud_shop?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
env:
  dev
